name: Minify Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Minifiers
        run: |
          npm install html-minifier-terser -g
          npm install clean-css-cli -g
          npm install terser -g

      - name: Add npm global bin to PATH
        run: echo "$(npm config get prefix)/bin" >> $GITHUB_PATH

      - name: Minify HTML files
        run: |
          for file in *.html; do
            echo "Minifying $file"
            html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true -o "$file" "$file"
          done

      - name: Minify CSS files
        run: |
          for file in *.css; do
            echo "Minifying $file"
            cleancss -o "$file" "$file"
          done

      - name: Minify JavaScript files
        run: |
          for file in *.js; do
            echo "Minifying $file"
            terser "$file" -o "$file"
          done

      - name: List files before deployment
        run: ls -l

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
